chdir "./SeaStSim"
"../../bin/SeaStateDriver_x64.exe" "./seastate_driver.inp"
chdir "../HDSim"
"../../bin/HydroDynDriver_x64.exe" "./hd_driver.inp"
chdir "../FASTSim"
"../../bin/openfast_x64.exe" "./fast_driver.fst"